name: Sync to Gitee
on: [push] # 只要 GitHub 有更新就同步，比定时更科学

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror action
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Jessy-Huang/embodied-ai-weekly.git"
          destination-repo: "git@gitee.com:jessy-huang/embodied-ai-weekly.git"