name: Sync to Gitee
on: [push, workflow_dispatch]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 读取 GitHub 用 HTTPS，不需要钥匙
          source-repo: "https://github.com/Jessy-Huang/embodied-ai-weekly.git"
          # 写入 Gitee 用 SSH，使用上面的钥匙
          destination-repo: "git@gitee.com:jessy-huang/embodied-ai-weekly.git"